name: Compile for Download

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                include:
                - os: macos-latest
                  SETUP: ./setup.sh
                  DOWNLOAD: brew install scons
                  PLATFORM: osx
                  EXTENSION: 64
                  SCONS_OPTIONS: arch=x86_64 -j3
                - os: ubuntu-latest
                  SETUP: ./setup.sh
                  DOWNLOAD: sudo apt update && sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
                  PLATFORM: x11
                  EXTENSION: 64
                  SCONS_OPTIONS: -j2
                - os: windows-latest
                  SETUP: .\setup.bat
                  DOWNLOAD: python -m pip install scons
                  PLATFORM: windows
                  EXTENSION: 64.exe
                  SCONS_OPTIONS: -j2
            fail-fast: false
        steps:
        - uses: actions/checkout@v2
          with: 
            repository: 'godotengine/godot'
            ref: '3.2.3-stable'
            
        - uses: actions/checkout@v2
          with:
            path: 'modules/godotcord'

        - name: Download Discord Game SDK
          working-directory: modules/godotcord
          run: ${{matrix.SETUP}}

        - run: ${{matrix.DOWNLOAD}}

        - name: Compile with target=release_debug
          run: scons bits=64 target=release_debug ${{matrix.SCONS_OPTIONS}}

        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: godotcord-binary-${{matrix.os}}
            path: bin/godot.${{matrix.PLATFORM}}.opt.tools.${{matrix.EXTENSION}}

        - name: Compile with target=debug
          run: scons bits=64 target=debug ${{matrix.SCONS_OPTIONS}}

        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: godotcord-binary-${{matrix.os}}-debug
            path: bin/godot.${{matrix.PLATFORM}}.tools.${{matrix.EXTENSION}}
